CREATE TABLE tb_email (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	destinatario VARCHAR(255) NOT NULL,
	titulo VARCHAR(255) NOT NULL,
	corpo VARCHAR(255)
);

CREATE TABLE tb_perfil (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL
);

CREATE TABLE tb_usuario (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	nome VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	perfil_id BIGINT NOT NULL
);